import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/Project";

import "./page.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation name="page" />
      {children}
    </>
  );
}
